name: Build and Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Preferences.slnx
      
      - name: Build
        run: dotnet build Preferences.slnx --configuration Release --no-restore

      - name: Publish to NuGet.org
        run: dotnet nuget push **/Preferences.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate